=== Open-Inflation/pyaterochka_api/tests/__snapshots__/ClassCatalog.tree_extended.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "description": {
      "type": "null"
    },
    "description_html": {
      "type": "null"
    },
    "image_link": {
      "type": "null"
    },
    "gradient_start": {
      "type": "string"
    },
    "gradient_end": {
      "type": "string"
    },
    "title_color": {
      "type": "string"
    },
    "advert": {
      "type": "null"
    },
    "categories_tags": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name"
        ]
      }
    },
    "additional_icons": {
      "type": "array"
    }
  },
  "required": [
    "additional_icons",
    "advert",
    "categories_tags",
    "description",
    "description_html",
    "gradient_end",
    "gradient_start",
    "id",
    "image_link",
    "name",
    "title_color"
  ]
}

=== Open-Inflation/pyaterochka_api/tests/__snapshots__/ClassCatalog.tree_extended.json
{
  "id": "251C17045",
  "name": "Пятёрочка выручает!",
  "description": null,
  "description_html": null,
  "image_link": null,
  "gradient_start": "#F6726A",
  "gradient_end": "#C64E46",
  "title_color": "#000000",
  "advert": null,
  "categories_tags": [
    {
      "id": "251C17046",
      "name": "Скидки недели"
    },
    {
      "id": "251C17047",
      "name": "Выгодно"
    },
    {
      "id": "251C17048",
      "name": "Новинки с доставкой"
    }
  ],
  "additional_icons": []
}
