=== Open-Inflation/pyaterochka_api/tests/__snapshots__/ClassCatalog.products_list.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "parent_id": {
      "type": "null"
    },
    "name": {
      "type": "string"
    },
    "filters": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "field_name": {
            "type": "string"
          },
          "filter_type": {
            "type": "string"
          },
          "list_values": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "object",
                "properties": {
                  "all": {
                    "type": "null"
                  },
                  "actual": {
                    "type": "null"
                  }
                },
                "required": [
                  "actual",
                  "all"
                ]
              }
            ]
          },
          "range_min_val": {
            "type": "null"
          },
          "range_max_val": {
            "type": "null"
          }
        },
        "required": [
          "field_name",
          "filter_type",
          "list_values",
          "name",
          "range_max_val",
          "range_min_val"
        ]
      }
    },
    "products": {
      "type": "array"
    }
  },
  "required": [
    "filters",
    "name",
    "parent_id",
    "products"
  ]
}

=== Open-Inflation/pyaterochka_api/tests/__snapshots__/ClassCatalog.products_list.json
{
  "parent_id": "0",
  "name": "Пятёрочка выручает!",
  "filters": [
    {
      "name": "Цена, ₽",
      "field_name": "price",
      "filter_type": "range",
      "list_values": null,
      "range_min_val": "9.99",
      "range_max_val": "1499.00"
    },
    {
      "name": "Бренд",
      "field_name": "brand",
      "filter_type": "list",
      "list_values": {
        "all": [
          "Global Village",
          "Fish House",
          "Econta",
          "Level Kitchen",
          "Агуша",
          "Рестория",
          "Сады Придонья",
          "Хамелеон",
          "Шарлиз",
          "Liberhaus",
          "Выручай",
          "Mixbar",
          "Bodyart",
          "Мираторг",
          "Honey Kid",
          "Добрый",
          "Черкизово",
          "Sheba",
          "Красная цена",
          "Махеевъ",
          "Папа может",
          "Фрутмотив",
          "Вкус & Польза",
          "Селяночка",
          "Хлебный Дом",
          "Alphachef",
          "Красный октябрь",
          "Святой Источник",
          "Dingo",
          "Endeavor",
          "Katty Pro",
          "Stardent",
          "Tolli",
          "Без бренда",
          "Хрутка",
          "Ariel",
          "Dolce Milk",
          "Garnier",
          "Jinmailang",
          "Lamm",
          "Papia",
          "Splat",
          "Белая Дача",
          "Вязанка",
          "Горячая штучка",
          "Зерница",
          "ИндиЛайт",
          "Коломенское",
          "Персил",
          "Рексона",
          "Сарафаново",
          "У Палыча",
          "Goodmix",
          "Hochland",
          "Konti",
          "Neo",
          "Sибирская коллекция",
          "Брест-Литовск",
          "Велком",
          "Село Зеленое",
          "Фили-Бейкер",
          "Assand",
          "Astoria",
          "Casademont",
          "Felix",
          "Flash Up",
          "Laplandia",
          "Mirel",
          "Nemoloko",
          "Peros",
          "Snickers",
          "Tide",
          "АктиБио",
          "Барни",
          "Бон Пари",
          "Глисс Кур",
          "Караван-Сарай",
          "Лоск",
          "Палетт",
          "Петелинка",
          "Простоквашино",
          "Росинка",
          "Русское море",
          "Сьёсс",
          "Фабрика им. Крупской",
          "ФрутоНяня",
          "Чудо",
          "Юбилейное",
          "Alpen Gold",
          "Bionova",
          "BombBar",
          "Chupa Chups",
          "Egoiste",
          "Grass",
          "Halls",
          "Jaguar",
          "Lay's",
          "Linmin",
          "Nivea",
          "ProteinRex"
        ],
        "actual": null
      },
      "range_min_val": null,
      "range_max_val": null
    },
    {
      "name": "Со скидкой",
      "field_name": "special_offers",
      "filter_type": "toggle",
      "list_values": {
        "all": [
          "1 + 1",
          "Скидка %",
          "% от количества"
        ],
        "actual": null
      },
      "range_min_val": null,
      "range_max_val": null
    }
  ],
  "products": [
    {
      "plu": 3395339,
      "name": "Кофе Egoiste Noir молотый 250г",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1168633-main/320x320.jpeg?updated_at=2025-01-31T14:11:57.593Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1168633-main/800x800.jpeg?updated_at=2025-01-31T14:11:57.593Z",
          "https://catalog-images.x5static.net/product/ba2653c5bf60bbbaaf1a1172cb085d76-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/4554e5c39733ee63941b3a4f971e40c5-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/e05db61b722c4f81b4314ff7cfd723bc-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 5.0,
        "rates_count": 10
      },
      "promo": null,
      "prices": {
        "regular": "999.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "250 г",
      "has_age_restriction": false,
      "stock_limit": "3.00",
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 630,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4327381,
      "name": "Виноград Шайн Мускат нефритовый",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1623007-main/320x320.jpeg?updated_at=2025-09-24T17:36:02.279Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1623007-main/800x800.jpeg?updated_at=2025-09-24T17:36:02.279Z",
          "https://catalog-images.x5static.net/product/b724f1f4a0ad1084cbc9800cb26ffcc4-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/258e07caeb95c4c33e30d27e48e6545c-additional/800x800.jpeg"
        ]
      },
      "uom": "кг",
      "step": "1.1",
      "rating": {
        "rating_average": 4.83,
        "rates_count": 15709
      },
      "promo": null,
      "prices": {
        "regular": "399.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "Цена за 1 кг",
      "has_age_restriction": false,
      "stock_limit": "48.00",
      "badges": [],
      "initial_weight_step": "1.1",
      "min_weight": "1.1",
      "orange_loyalty_points": 210,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4225898,
      "name": "Вино Free Feather безалкогольное газированное сладкое белое 0.75л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1488585-main/320x320.jpeg?updated_at=2025-03-11T20:38:21.773Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1488585-main/800x800.jpeg?updated_at=2025-03-11T20:38:21.773Z"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": null,
      "promo": null,
      "prices": {
        "regular": "799.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "750 мл",
      "has_age_restriction": false,
      "stock_limit": "9.00",
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 490,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 3406629,
      "name": "Зефир Шарлиз глазированный ваниль 240г",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1169170-main/320x320.jpeg?updated_at=2025-09-25T10:28:53.508Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1169170-main/800x800.jpeg?updated_at=2025-09-25T10:28:53.508Z"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.84,
        "rates_count": 13066
      },
      "promo": null,
      "prices": {
        "regular": "169.99",
        "discount": "99.99",
        "cpd_promo_price": null
      },
      "labels": [
        {
          "label": "-41%",
          "bg_color": "#FFD700",
          "text_color": "#302E33"
        }
      ],
      "property_clarification": "240 г",
      "has_age_restriction": false,
      "stock_limit": "0.00",
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": null,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 29866,
      "name": "Помело розовое",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1157869-main/320x320.jpeg?updated_at=2025-03-12T07:06:20.501Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1157869-main/800x800.jpeg?updated_at=2025-03-12T07:06:20.501Z",
          "https://catalog-images.x5static.net/product/73e68b09a514a66025d1e382e7e1b3ce-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/b7fe0a7f0120d5db891e58c5e8c966aa-additional/800x800.jpeg"
        ]
      },
      "uom": "кг",
      "step": "1.2",
      "rating": {
        "rating_average": 4.69,
        "rates_count": 8338
      },
      "promo": null,
      "prices": {
        "regular": "179.99",
        "discount": "159.99",
        "cpd_promo_price": null
      },
      "labels": [
        {
          "label": "-11%",
          "bg_color": "#FFD700",
          "text_color": "#302E33"
        }
      ],
      "property_clarification": "Цена за 1 кг",
      "has_age_restriction": false,
      "stock_limit": "5.05",
      "badges": [],
      "initial_weight_step": "1.2",
      "min_weight": "1.2",
      "orange_loyalty_points": null,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4297371,
      "name": "Конфеты шоколадные Коркунов Коллекция из темного и молочного шоколада с фундуком и вафельной крошкой 165г",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1511851-main/320x320.jpeg?updated_at=2025-10-17T12:23:32.022Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1511851-main/800x800.jpeg?updated_at=2025-10-17T12:23:32.022Z",
          "https://catalog-images.x5static.net/product/f8038844d82ea67655db25656d909a3c-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/19ea51418e9fa2a9a300eb776fbcada3-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/e1fe1d6e295b28fbb5b33ad9db9372f5-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/cd957347b33199d877c76de2e765d531-additional/800x800.jpeg",
