=== Open-Inflation/pyaterochka_api/tests/__snapshots__/ClassCatalog.search.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "search_query_id": {
      "format": "uuid",
      "type": "string"
    },
    "query_type": {
      "type": "string"
    },
    "products": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "plu": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "image_links": {
            "type": "object",
            "properties": {
              "small": {
                "type": "array",
                "items": {
                  "format": "uri",
                  "type": "string"
                }
              },
              "normal": {
                "type": "array",
                "items": {
                  "format": "uri",
                  "type": "string"
                }
              }
            },
            "required": [
              "normal",
              "small"
            ]
          },
          "uom": {
            "type": "string"
          },
          "step": {
            "type": "string"
          },
          "rating": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "object",
                "properties": {
                  "rating_average": {
                    "type": "number"
                  },
                  "rates_count": {
                    "type": "integer"
                  }
                },
                "required": [
                  "rates_count",
                  "rating_average"
                ]
              }
            ]
          },
          "promo": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "object",
                "properties": {
                  "rebate": {
                    "type": "object",
                    "properties": {
                      "units_to_activate": {
                        "type": "integer"
                      }
                    },
                    "required": [
                      "units_to_activate"
                    ]
                  }
                },
                "required": [
                  "rebate"
                ]
              }
            ]
          },
          "prices": {
            "type": "object",
            "properties": {
              "regular": {
                "type": "string"
              },
              "discount": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "cpd_promo_price": {
                "type": [
                  "null",
                  "string"
                ]
              }
            },
            "required": [
              "cpd_promo_price",
              "discount",
              "regular"
            ]
          },
          "labels": {
            "anyOf": [
              {
                "type": "null"
              },
              {
                "type": "array",
                "items": {
                  "type": "object",
                  "properties": {
                    "label": {
                      "type": "string"
                    },
                    "bg_color": {
                      "type": "string"
                    },
                    "text_color": {
                      "type": "string"
                    },
                    "icon_url": {
                      "type": "null"
                    }
                  },
                  "required": [
                    "bg_color",
                    "label",
                    "text_color"
                  ]
                }
              }
            ]
          },
          "property_clarification": {
            "type": "string"
          },
          "has_age_restriction": {
            "type": "boolean"
          },
          "stock_limit": {
            "type": "string"
          },
          "product_advert": {
            "type": "null"
          },
          "is_large_card": {
            "type": "null"
          },
          "boost_type": {
            "type": "null"
          },
          "badges": {
            "type": "array"
          },
          "initial_weight_step": {
            "type": "string"
          },
          "min_weight": {
            "type": "string"
          },
          "orange_loyalty_points": {
            "type": [
              "integer",
              "null"
            ]
          },
          "is_available": {
            "type": "boolean"
          },
          "price_piece_unit": {
            "type": "null"
          }
        },
        "required": [
          "badges",
          "boost_type",
          "has_age_restriction",
          "image_links",
          "initial_weight_step",
          "is_available",
          "is_large_card",
          "labels",
          "min_weight",
          "name",
          "orange_loyalty_points",
          "plu",
          "price_piece_unit",
          "prices",
          "product_advert",
          "promo",
          "property_clarification",
          "rating",
          "step",
          "stock_limit",
          "uom"
        ]
      }
    },
    "categories": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "parent_name": {
            "type": "string"
          }
        },
        "required": [
          "id",
          "name",
          "parent_name",
          "type"
        ]
      }
    }
  },
  "required": [
    "categories",
    "products",
    "query_type",
    "search_query_id"
  ]
}

=== Open-Inflation/pyaterochka_api/tests/__snapshots__/ClassCatalog.search.json
{
  "search_query_id": "a0b891f6-ad77-43bd-9d11-849e4fcb2e77",
  "query_type": "strict",
  "products": [
    {
      "plu": 4429993,
      "name": "Напиток Кола Добрый с пониженной калорийностью газированный 1л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/2063329-main/320x320.jpeg?updated_at=2025-09-29T11:29:23.079Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/2063329-main/800x800.jpeg?updated_at=2025-09-29T11:29:23.079Z"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.85,
        "rates_count": 9332
      },
      "promo": null,
      "prices": {
        "regular": "89.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "1 л",
      "has_age_restriction": false,
      "stock_limit": "32.00",
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 62,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4042943,
      "name": "Крем для лица Tolk Pharm Коллаген косметический 40мл",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1454261-main/320x320.jpeg?updated_at=2025-05-02T17:09:37.403Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1454261-main/800x800.jpeg?updated_at=2025-05-02T17:09:37.403Z",
          "https://catalog-images.x5static.net/product/20d6eaf4fdfed9ffab2c5f7eef85cd01-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/ff83f746e9a244ef15c3444a56898fae-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": null,
      "promo": null,
      "prices": {
        "regular": "189.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "40 мл",
      "has_age_restriction": false,
      "stock_limit": "0.00",
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 70,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4316013,
      "name": "Напиток Любимая Кола газированный 2л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1574988-main/320x320.jpeg?updated_at=2025-01-31T14:19:44.790Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1574988-main/800x800.jpeg?updated_at=2025-01-31T14:19:44.790Z",
          "https://catalog-images.x5static.net/product/8b65d972fa99ee3323f2ca3a1312cb17-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/1940005236f27382cfbf8e7eaed84e49-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.86,
        "rates_count": 243
      },
      "promo": null,
      "prices": {
        "regular": "217.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "2 л",
      "has_age_restriction": false,
      "stock_limit": "5.00",
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 140,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4279793,
      "name": "Напиток Любимая Кола газированный 1л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1502059-main/320x320.jpeg?updated_at=2025-01-13T06:06:50.056Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1502059-main/800x800.jpeg?updated_at=2025-01-13T06:06:50.056Z",
          "https://catalog-images.x5static.net/product/1e53600e3ed291d4bb355d53f2429494-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/45af3f26bb4cc5194585dc8e50bd5aa4-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/77bea9ce06ff45b1a99aaa4bbef93824-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/bd2f0ebbb6e6e624928b76f5a3cb4064-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/fca49911061e7eeae8943ad1767e1d65-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.6,
        "rates_count": 11
      },
      "promo": null,
      "prices": {
        "regular": "117.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "1 л",
      "has_age_restriction": false,
      "stock_limit": "23.00",
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 70,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4279795,
      "name": "Напиток газированный Любимая Кола 1.5л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1499734-main/320x320.jpeg?updated_at=2024-12-24T14:28:46.464Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1499734-main/800x800.jpeg?updated_at=2024-12-24T14:28:46.464Z",
          "https://catalog-images.x5static.net/product/006f1beddcd43d21ed03d8a3567275a7-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.3,
        "rates_count": 10
      },
      "promo": null,
      "prices": {
        "regular": "190.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "1.5 л",
      "has_age_restriction": false,
      "stock_limit": "9.00",
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 70,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4279789,
      "name": "Напиток Любимая Кола газированный 500мл",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1506044-main/320x320.jpeg?updated_at=2025-01-31T14:19:42.485Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1506044-main/800x800.jpeg?updated_at=2025-01-31T14:19:42.485Z",
          "https://catalog-images.x5static.net/product/a6d7e74b9b0a08bf041ec325f02b860f-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/9fa4ed6bc6c9e81c57647f66bafdb6c6-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/65b5e5d0e7b9503dd06860b18c26752e-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/d7032517d1a8acbea560eb34e7caa000-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.79,
        "rates_count": 175
      },
      "promo": null,
      "prices": {
        "regular": "89.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "500 мл",
      "has_age_restriction": false,
      "stock_limit": "7.00",
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 62,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4279817,
      "name": "Напиток Любимая Кола газированный 0.33л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1499712-main/320x320.jpeg?updated_at=2025-02-24T13:19:20.998Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1499712-main/800x800.jpeg?updated_at=2025-02-24T13:19:20.998Z",
          "https://catalog-images.x5static.net/product/be00b99a8d24d398f088368270fc8f36-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/cd157eb52fd951628b37992dca4026f3-additional/800x800.jpeg"
        ]
      },
      "uom": "шт",
      "step": "1.0",
      "rating": {
        "rating_average": 4.75,
        "rates_count": 12
      },
      "promo": null,
      "prices": {
        "regular": "65.99",
        "discount": null,
        "cpd_promo_price": null
      },
      "labels": null,
      "property_clarification": "330 мл",
      "has_age_restriction": false,
      "stock_limit": "0.00",
      "product_advert": null,
      "is_large_card": null,
      "boost_type": null,
      "badges": [],
      "initial_weight_step": "1.0",
      "min_weight": "1.0",
      "orange_loyalty_points": 46,
      "is_available": true,
      "price_piece_unit": null
    },
    {
      "plu": 4213891,
      "name": "Напиток Черноголовка Кола 2л",
      "image_links": {
        "small": [
          "https://catalog-images.x5static.net/product/1447700-main/320x320.jpeg?updated_at=2025-10-29T10:37:30.311Z"
        ],
        "normal": [
          "https://catalog-images.x5static.net/product/1447700-main/800x800.jpeg?updated_at=2025-10-29T10:37:30.311Z",
          "https://catalog-images.x5static.net/product/a7200adf71f9bc86383293a7dde3ba2c-additional/800x800.jpeg",
          "https://catalog-images.x5static.net/product/b6428af12e388b318a321d45f3e630a2-additional/800x800.jpeg",
