=== Open-Inflation/pyaterochka_api/tests/__snapshots__/PyaterochkaAPI.delivery_panel_store.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "selectedAddress": {
      "type": "object",
      "properties": {
        "value": {
          "type": "null"
        },
        "coordinates": {
          "type": "array"
        },
        "sapCode": {
          "type": "string"
        },
        "shopAddress": {
          "type": "string"
        }
      },
      "required": [
        "coordinates",
        "sapCode",
        "shopAddress",
        "value"
      ]
    },
    "selectedStore": {
      "type": "object",
      "properties": {
        "coordinates": {
          "type": "array"
        },
        "sapCode": {
          "type": "string"
        },
        "shopAddress": {
          "type": "string"
        }
      },
      "required": [
        "coordinates",
        "sapCode",
        "shopAddress"
      ]
    },
    "filterData": {
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "source": {
          "type": "array"
        },
        "loadingState": {
          "type": "integer"
        },
        "coordinates": {
          "type": "array"
        },
        "selectedItem": {
          "type": "null"
        },
        "hasDelivery": {
          "type": "integer"
        },
        "sapCode": {
          "type": "string"
        },
        "shopAddress": {
          "type": "string"
        },
        "error": {
          "type": "null"
        }
      },
      "required": [
        "coordinates",
        "error",
        "hasDelivery",
        "loadingState",
        "sapCode",
        "selectedItem",
        "shopAddress",
        "source",
        "value"
      ]
    },
    "geoPositionError": {
      "type": "boolean"
    },
    "fetchApplyPrevAddress": {
      "type": "integer"
    },
    "isReadyForStorage": {
      "type": "boolean"
    }
  },
  "required": [
    "fetchApplyPrevAddress",
    "filterData",
    "geoPositionError",
    "isReadyForStorage",
    "selectedAddress",
    "selectedStore"
  ]
}

=== Open-Inflation/pyaterochka_api/tests/__snapshots__/PyaterochkaAPI.delivery_panel_store.json
{
  "selectedAddress": {
    "value": null,
    "coordinates": [],
    "sapCode": "35XY",
    "shopAddress": "Москва, Севастопольский проспект, 28к2"
  },
  "selectedStore": {
    "coordinates": [],
    "sapCode": "35XY",
    "shopAddress": "Москва, Севастопольский проспект, 28к2"
  },
  "filterData": {
    "value": "",
    "source": [],
    "loadingState": 0,
    "coordinates": [],
    "selectedItem": null,
    "hasDelivery": 0,
    "sapCode": "35XY",
    "shopAddress": "Москва, Севастопольский проспект, 28к2",
    "error": null
  },
  "geoPositionError": false,
  "fetchApplyPrevAddress": 6,
  "isReadyForStorage": true
}
